### ISSUE TITLE
Have to manually create some directories before running

### ISSUE THREAD

**Issue by Anen** [immortius/gw2-wardrobe-unlock#2]
Just build the app on OSX. I had to manually create some directories to overcome the below error.
site/data
cache/prices
cache/gwu
cache/vendors

```
Exception in thread "main" java.nio.file.NoSuchFileException: cache/prices/armor.json
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:222)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2994)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3037)
        at au.net.immortius.wardrobe.gw2api.PullCurrentPrices.run(PullCurrentPrices.java:118)
        at au.net.immortius.wardrobe.UpdateSite.main(UpdateSite.java:39)
```

**Comment by immortius** [comment]
Will fix!

**Comment by immortius** [comment]
This should be fixed now.

**Comment by Anen** [comment]
It seems like the call mentionned in the first error log in PullCurrentPrices.run isn't fixed as I still got the error when rebuilding from scratch.
